import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "./components/Navigation";
import MainBanner from "./components/MainBanner";
import { ambilIdentitas } from "@/lib/dashboardApi";
import Footer from "./components/Footer";
import PartnerStyle2 from "./components/PartnerStyle2";
import About from "./components/About";
import Category from "./components/Category";
import Layout from "./components/Layout";
import Process from "./components/Process";
import GoTop from "./components/GoTop";
import Timevenue from "./components/Timevenue";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ identitas }) {
  return (
    <>
      <Head>
        <title>IYMIA - International Young Moslem Inventor Award </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <Navbar />
      <MainBanner identitas={identitas} />
      <PartnerStyle2 />
      <About />
      {/* <Timevenue /> */}
      <Category />
      <Layout />
      <Process />
      <GoTop />
      <Footer />
    </>
  );
}

/** Identitas edisi ditarik saat halaman dibangun ulang — lima menit, sama
 *  dengan umur cache API-nya. */
export async function getStaticProps() {
  return { props: { identitas: await ambilIdentitas() }, revalidate: 300 };
}
