import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "./components/Navigation";
import MainBanner from "./components/MainBanner";
import Footer from "./components/Footer";
import PartnerStyle2 from "./components/PartnerStyle2";
import About from "./components/About";
import Category from "./components/Category";
import Layout from "./components/Layout";
import Process from "./components/Process";
import GoTop from "./components/GoTop";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>IYMIA - International Young Moslem Inventor Award </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <Navbar />
      <MainBanner />
      <About/>
      <Category/>
      <Layout/>
      <Process/>
      <PartnerStyle2 />
      <GoTop/>
      <Footer/>
    </>
  );
}
