import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "./components/Navigation";
import MainBanner from "./components/MainBanner";
import { ambilGuidebook, ambilIdentitas } from "@/lib/dashboardApi";
import Footer from "./components/Footer";
import PartnerStyle2 from "./components/PartnerStyle2";
import About from "./components/About";
import Category from "./components/Category";
import Layout from "./components/Layout";
import Process from "./components/Process";
import GoTop from "./components/GoTop";
import Timevenue from "./components/Timevenue";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ identitas, guidebook }) {
  return (
    <>
      <Head>
        <title>IYMIA - International Young Moslem Inventor Award </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <Navbar />
      <MainBanner identitas={identitas} guidebook={guidebook} />
      <PartnerStyle2 />
      <About />
      {/* <Timevenue /> */}
      <Category />
      <Layout />
      <Process />
      <GoTop />
      <Footer />
    </>
  );
}

/** Identitas edisi ditarik saat halaman dibangun ulang — lima menit, sama
 *  dengan umur cache API-nya. */
export async function getStaticProps() {
  /* Keduanya diambil berbarengan — dua panggilan berurutan menambah tunggu
     tanpa alasan, dan yang satu tidak bergantung hasil yang lain. */
  const [identitas, guidebook] = await Promise.all([ambilIdentitas(), ambilGuidebook()]);
  /* Satu menit, bukan lima. Yang paling sering ditunggu sesudah panitia
     menekan "Terbitkan ke situs" adalah tombol Guidebook di spanduk ini; lima
     menit terasa seperti tidak terjadi apa-apa. Spanduk juga menyegarkan
     dirinya sendiri di peramban — lihat `MainBanner`. */
  return { props: { identitas, guidebook }, revalidate: 60 };
}
